In [1]:
import numpy as np
import torch

In [ ]:
torch.__version__

# First steps with PyTorch

Follow along as I live code my way through chapter 12 of [*Machine Learning with Scikit-Learn and PyTorch*](https://github.com/rasbt/machine-learning-book)!

In [2]:
a = [1, 4.5, 6.0, 3.33, 2 / 3]

In [ ]:
np.array?

In [14]:
b = np.array(a, dtype=np.float32)

In [15]:
b

array([1.       , 4.5      , 6.       , 3.33     , 0.6666667],
      dtype=float32)

In [ ]:
torch.tensor?

In [16]:
t_a = torch.tensor(a, dtype=torch.float32)

In [17]:
t_a

tensor([1.0000, 4.5000, 6.0000, 3.3300, 0.6667])

In [ ]:
torch.from_numpy?

In [18]:
t_b = torch.from_numpy(b)

In [19]:
t_b

tensor([1.0000, 4.5000, 6.0000, 3.3300, 0.6667])

In [ ]:
torch.ones?

In [22]:
c = torch.ones(2, 3)

In [24]:
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [23]:
c.shape

torch.Size([2, 3])

In [ ]:
torch.rand?

In [ ]:
torch.manual_seed?

In [25]:
d = torch.rand(2, 3)

In [26]:
d

tensor([[0.7496, 0.7024, 0.0408],
        [0.8834, 0.9521, 0.6744]])

## Manipulating the type and shape of tensors

In [27]:
t_a.to(torch.int64)

tensor([1, 4, 6, 3, 0])

In [28]:
t_a

tensor([1.0000, 4.5000, 6.0000, 3.3300, 0.6667])

In [29]:
e = torch.rand(2, 3)
e

tensor([[0.4490, 0.2584, 0.0780],
        [0.5300, 0.2313, 0.2962]])

In [ ]:
torch.transpose?

In [31]:
e_t = torch.transpose(e, 0, 1)

In [32]:
e_t

tensor([[0.4490, 0.5300],
        [0.2584, 0.2313],
        [0.0780, 0.2962]])

In [39]:
e.transpose(0, 1)

tensor([[0.4490, 0.5300],
        [0.2584, 0.2313],
        [0.0780, 0.2962]])

In [35]:
f = torch.rand(40)
f

tensor([0.8371, 0.0672, 0.6873, 0.2110, 0.6358, 0.3508, 0.2168, 0.5029, 0.4843,
        0.5116, 0.2024, 0.9747, 0.2964, 0.5956, 0.3181, 0.9539, 0.1753, 0.2507,
        0.0677, 0.7462, 0.2386, 0.2159, 0.1508, 0.2510, 0.6150, 0.9866, 0.0064,
        0.2209, 0.2317, 0.7072, 0.8961, 0.1990, 0.3097, 0.7888, 0.3396, 0.4539,
        0.6686, 0.4744, 0.9785, 0.7249])

In [37]:
torch.reshape?

In [38]:
torch.reshape(f, (5, 8))

tensor([[0.8371, 0.0672, 0.6873, 0.2110, 0.6358, 0.3508, 0.2168, 0.5029],
        [0.4843, 0.5116, 0.2024, 0.9747, 0.2964, 0.5956, 0.3181, 0.9539],
        [0.1753, 0.2507, 0.0677, 0.7462, 0.2386, 0.2159, 0.1508, 0.2510],
        [0.6150, 0.9866, 0.0064, 0.2209, 0.2317, 0.7072, 0.8961, 0.1990],
        [0.3097, 0.7888, 0.3396, 0.4539, 0.6686, 0.4744, 0.9785, 0.7249]])

In [36]:
f.reshape(5, 8)

tensor([[0.8371, 0.0672, 0.6873, 0.2110, 0.6358, 0.3508, 0.2168, 0.5029],
        [0.4843, 0.5116, 0.2024, 0.9747, 0.2964, 0.5956, 0.3181, 0.9539],
        [0.1753, 0.2507, 0.0677, 0.7462, 0.2386, 0.2159, 0.1508, 0.2510],
        [0.6150, 0.9866, 0.0064, 0.2209, 0.2317, 0.7072, 0.8961, 0.1990],
        [0.3097, 0.7888, 0.3396, 0.4539, 0.6686, 0.4744, 0.9785, 0.7249]])

In [40]:
g = torch.rand(1, 2, 1, 4, 5)
g

tensor([[[[[0.1973, 0.0514, 0.4273, 0.5294, 0.4435],
           [0.5994, 0.5222, 0.5144, 0.6194, 0.7200],
           [0.8643, 0.6407, 0.5361, 0.9361, 0.2588],
           [0.7083, 0.0184, 0.4278, 0.8650, 0.9236]]],


         [[[0.3274, 0.5968, 0.3151, 0.5437, 0.3140],
           [0.8752, 0.5365, 0.0156, 0.7385, 0.6914],
           [0.8447, 0.9882, 0.2469, 0.7298, 0.8151],
           [0.0271, 0.0761, 0.9519, 0.6246, 0.5269]]]]])

In [41]:
g.shape

torch.Size([1, 2, 1, 4, 5])

In [43]:
h = torch.squeeze(g, 2)

In [44]:
h.shape

torch.Size([1, 2, 4, 5])

In [45]:
j = h.squeeze(0)

In [46]:
j.shape

torch.Size([2, 4, 5])

## Applying mathematical operators to tensors

In [48]:
prng = torch.manual_seed(1234)

In [51]:
t1 = 2 * torch.rand(5, 2, generator=prng) - 1

In [52]:
t1

tensor([[-0.9420, -0.1962],
        [-0.4803, -0.2667],
        [-0.8834,  0.4013],
        [-0.8964, -0.0637],
        [ 0.3476, -0.3371]])

In [54]:
t2 = torch.normal(mean=0, std=1, size=(5,2), generator=prng)

In [55]:
t2

tensor([[-0.0821,  0.6607],
        [ 0.0785,  0.7884],
        [ 1.5385, -0.9757],
        [ 1.5769,  0.3840],
        [-0.6039, -0.5240]])

In [56]:
torch.multiply(t1, t2)

tensor([[ 0.0773, -0.1296],
        [-0.0377, -0.2103],
        [-1.3591, -0.3916],
        [-1.4136, -0.0245],
        [-0.2099,  0.1766]])

In [57]:
t1.multiply(t2)

tensor([[ 0.0773, -0.1296],
        [-0.0377, -0.2103],
        [-1.3591, -0.3916],
        [-1.4136, -0.0245],
        [-0.2099,  0.1766]])

In [58]:
t1 * t2

tensor([[ 0.0773, -0.1296],
        [-0.0377, -0.2103],
        [-1.3591, -0.3916],
        [-1.4136, -0.0245],
        [-0.2099,  0.1766]])

In [110]:
torch.mean(t1, dim=0)

tensor([-0.5709, -0.0925])

In [108]:
torch.std(t1, dim=1)

tensor([0.5274, 0.1510, 0.9084, 0.5888, 0.4841])

In [111]:
torch.sum(t1, dim=0)

tensor([-2.8545, -0.4624])

In [112]:
t1.sum(dim=0)

tensor([-2.8545, -0.4624])

In [65]:
torch.matmul(t1, t2.transpose(0, 1))

tensor([[-0.0523, -0.2286, -1.2579, -1.5609,  0.6717],
        [-0.1368, -0.2480, -0.4787, -0.8598,  0.4298],
        [ 0.3376,  0.2471, -1.7507, -1.2390,  0.3232],
        [ 0.0315, -0.1206, -1.3170, -1.4380,  0.5747],
        [-0.2512, -0.2385,  0.8637,  0.4187, -0.0333]])

In [67]:
torch.matmul(t1, t2.T)

tensor([[-0.0523, -0.2286, -1.2579, -1.5609,  0.6717],
        [-0.1368, -0.2480, -0.4787, -0.8598,  0.4298],
        [ 0.3376,  0.2471, -1.7507, -1.2390,  0.3232],
        [ 0.0315, -0.1206, -1.3170, -1.4380,  0.5747],
        [-0.2512, -0.2385,  0.8637,  0.4187, -0.0333]])

In [66]:
t1 @ t2.T

tensor([[-0.0523, -0.2286, -1.2579, -1.5609,  0.6717],
        [-0.1368, -0.2480, -0.4787, -0.8598,  0.4298],
        [ 0.3376,  0.2471, -1.7507, -1.2390,  0.3232],
        [ 0.0315, -0.1206, -1.3170, -1.4380,  0.5747],
        [-0.2512, -0.2385,  0.8637,  0.4187, -0.0333]])

In [69]:
t1.T @ t2

tensor([[-2.9430, -0.6655],
        [ 0.7156, -0.5793]])

In [68]:
torch.dot(t1, t2.T)

RuntimeError: ignored

In [70]:
torch.linalg.norm?

In [72]:
torch.linalg.norm(t2, ord=2, dim=0)

tensor([2.2872, 1.5596])

In [106]:
torch.sqrt(torch.sum(t2**2, dim=0))

tensor([2.2872, 1.5596])

## Chunk, split, stack, and concatenate tensors

In [76]:
prng = torch.manual_seed(42)

In [82]:
t = torch.rand(10, 3, generator=prng)
t

tensor([[0.6343, 0.3644, 0.7104],
        [0.9464, 0.7890, 0.2814],
        [0.7886, 0.5895, 0.7539],
        [0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440],
        [0.7071, 0.6581, 0.4913],
        [0.8913, 0.1447, 0.5315],
        [0.1587, 0.6542, 0.3278],
        [0.6532, 0.3958, 0.9147],
        [0.2036, 0.2018, 0.2018]])

In [83]:
torch.chunk?

In [85]:
batches = torch.chunk(t, 3, dim=0)

In [86]:
for i, batch in enumerate(batches):
    print(batch)

tensor([[0.6343, 0.3644, 0.7104],
        [0.9464, 0.7890, 0.2814],
        [0.7886, 0.5895, 0.7539],
        [0.1952, 0.0050, 0.3068]])
tensor([[0.1165, 0.9103, 0.6440],
        [0.7071, 0.6581, 0.4913],
        [0.8913, 0.1447, 0.5315],
        [0.1587, 0.6542, 0.3278]])
tensor([[0.6532, 0.3958, 0.9147],
        [0.2036, 0.2018, 0.2018]])


In [88]:
features = torch.chunk(t, 3, dim=1)

for j, feature in enumerate(features):
    print(feature)

tensor([[0.6343],
        [0.9464],
        [0.7886],
        [0.1952],
        [0.1165],
        [0.7071],
        [0.8913],
        [0.1587],
        [0.6532],
        [0.2036]])
tensor([[0.3644],
        [0.7890],
        [0.5895],
        [0.0050],
        [0.9103],
        [0.6581],
        [0.1447],
        [0.6542],
        [0.3958],
        [0.2018]])
tensor([[0.7104],
        [0.2814],
        [0.7539],
        [0.3068],
        [0.6440],
        [0.4913],
        [0.5315],
        [0.3278],
        [0.9147],
        [0.2018]])


In [92]:
splits = torch.split(t, split_size_or_sections=[4, 4, 2], dim=0)

In [94]:
for i, split in enumerate(splits):
    print(split)

tensor([[0.6343, 0.3644, 0.7104],
        [0.9464, 0.7890, 0.2814],
        [0.7886, 0.5895, 0.7539],
        [0.1952, 0.0050, 0.3068]])
tensor([[0.1165, 0.9103, 0.6440],
        [0.7071, 0.6581, 0.4913],
        [0.8913, 0.1447, 0.5315],
        [0.1587, 0.6542, 0.3278]])
tensor([[0.6532, 0.3958, 0.9147],
        [0.2036, 0.2018, 0.2018]])


In [97]:
torch.stack?

In [96]:
a = torch.zeros(5)
b = torch.ones(5)

In [98]:
torch.stack([a, b], dim=0)

tensor([[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.]])

In [99]:
torch.stack([a, b], dim=1)

tensor([[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]])

In [101]:
torch.cat?

In [104]:
torch.cat([a, b], dim=0)

tensor([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [105]:
torch.cat([a, b], dim=1)

IndexError: ignored